
FROM debian:bullseye-slim

RUN apt-get update -qq \
 && apt-get install -y --no-install-recommends gcc time \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /src
COPY . /src

ENTRYPOINT ["/usr/bin/time","-v","sh","-c"]
CMD ["gcc -std=c99 -O2 /src/main.c -o /src/main.out && exec /src/main.out"]
